<a href="https://colab.research.google.com/github/Monika0501/Python_practice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
#import pandas
import pandas as pd

In [5]:
pd.__version__

'2.2.2'

In [6]:
#1.create Dataframe
df=pd.DataFrame([11,22,33],columns=["Col_Name"])
print(df)

   Col_Name
0        11
1        22
2        33

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [8]:
data = {
    "Name":["madhav","lalita","monika","Honey"],
    "age":[14,15,16,17],
    "salary":[9000,4000,5000,3000]

}

In [9]:
df=pd.DataFrame(data)
print(df)

     Name  age  salary
0  madhav   14    9000
1  lalita   15    4000
2  monika   16    5000
3   Honey   17    3000

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [11]:
#2.Basic Dataframe Understanding

In [ ]:
df.head(2) #top rows

     Name  age  salary
0  madhav   14    9000
1  lalita   15    4000

In [12]:
df.tail(2) #Last rows

     Name  age  salary
2  monika   16    5000
3   Honey   17    3000

In [13]:
df.shape

(4, 3)

In [14]:
df.columns

Index(['Name', 'age', 'salary'], dtype='object')

In [15]:
df.rename(columns={"salary":"Monthly Salary"},inplace=True)

In [16]:
df

     Name  age  Monthly Salary
0  madhav   14            9000
1  lalita   15            4000
2  monika   16            5000
3   Honey   17            3000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   age             4 non-null      int64
 2   Monthly Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [18]:
df.describe()

             age  Monthly Salary
count   4.000000         4.00000
mean   15.500000      5250.00000
std     1.290994      2629.95564
min    14.000000      3000.00000
25%    14.750000      3750.00000
50%    15.500000      4500.00000
75%    16.250000      6000.00000
max    17.000000      9000.00000

In [19]:
#Save and load data from csv

In [20]:
df.to_csv("Test_data.csv") #export data frame

In [21]:
load_df=pd.read_csv("Test_data.csv") #import dataframe
load_df

   Unnamed: 0    Name  age  Monthly Salary
0           0  madhav   14            9000
1           1  lalita   15            4000
2           2  monika   16            5000
3           3   Honey   17            3000

In [22]:
#Rows and columns-selection
#select column
df

     Name  age  Monthly Salary
0  madhav   14            9000
1  lalita   15            4000
2  monika   16            5000
3   Honey   17            3000

In [23]:
df[["Name"]] #if i want single column

     Name
0  madhav
1  lalita
2  monika
3   Honey

In [24]:
df[["Name","Monthly Salary"]]

     Name  Monthly Salary
0  madhav            9000
1  lalita            4000
2  monika            5000
3   Honey            3000

In [25]:
#select rows
#loc-index name based singal row
df.loc[df.Name=="madhav"]

     Name  age  Monthly Salary
0  madhav   14            9000

In [26]:
df.loc[(df.Name=="madhav") & (df['Monthly Salary']>=5000)] #selecting multiple rows using AND

     Name  age  Monthly Salary
0  madhav   14            9000

In [27]:
df.loc[0:2]

     Name  age  Monthly Salary
0  madhav   14            9000
1  lalita   15            4000
2  monika   16            5000

In [28]:
#iloc-index value based
df.iloc[0]

Name              madhav
age                   14
Monthly Salary      9000
Name: 0, dtype: object

In [29]:
df.iloc[0:2] # [start:stop:step]

     Name  age  Monthly Salary
0  madhav   14            9000
1  lalita   15            4000

In [30]:
#filter dataframe
df

     Name  age  Monthly Salary
0  madhav   14            9000
1  lalita   15            4000
2  monika   16            5000
3   Honey   17            3000

In [31]:
df["age"]>15

0    False
1    False
2     True
3     True
Name: age, dtype: bool

In [32]:
df_age_filter=df[df["age"]>=15]

In [33]:
df_age_filter

     Name  age  Monthly Salary
1  lalita   15            4000
2  monika   16            5000
3   Honey   17            3000

In [34]:
df[(df["age"]>=15) & (df["Monthly Salary"]>=5000)]

     Name  age  Monthly Salary
2  monika   16            5000

In [35]:
df.where(df["age"]>=15, other="Not Eligible")

           Name           age Monthly Salary
0  Not Eligible  Not Eligible   Not Eligible
1        lalita            15           4000
2        monika            16           5000
3         Honey            17           3000

In [ ]:
#Rows and columns- Operations(add,update,delete)

In [36]:
df

     Name  age  Monthly Salary
0  madhav   14            9000
1  lalita   15            4000
2  monika   16            5000
3   Honey   17            3000

In [37]:
#add new column
df["Team"]=["CEO","DA","CTO","BA"]
df

     Name  age  Monthly Salary Team
0  madhav   14            9000  CEO
1  lalita   15            4000   DA
2  monika   16            5000  CTO
3   Honey   17            3000   BA

In [38]:
df["Bonus"]=df["Monthly Salary"]*0.2
df

     Name  age  Monthly Salary Team   Bonus
0  madhav   14            9000  CEO  1800.0
1  lalita   15            4000   DA   800.0
2  monika   16            5000  CTO  1000.0
3   Honey   17            3000   BA   600.0

In [39]:
#add new row
df.loc[len(df)]=["ABC",21,2100,"IT",1000]
df

     Name  age  Monthly Salary Team   Bonus
0  madhav   14            9000  CEO  1800.0
1  lalita   15            4000   DA   800.0
2  monika   16            5000  CTO  1000.0
3   Honey   17            3000   BA   600.0
4     ABC   21            2100   IT  1000.0

In [40]:
len(df)

5

In [41]:
#update value
df.loc[0,"Monthly Salary"]=95000 #index name used
df

     Name  age  Monthly Salary Team   Bonus
0  madhav   14           95000  CEO  1800.0
1  lalita   15            4000   DA   800.0
2  monika   16            5000  CTO  1000.0
3   Honey   17            3000   BA   600.0
4     ABC   21            2100   IT  1000.0

In [42]:
#update value - using column value
df.loc[df.Name=="madhav","Monthly Salary"]=100000
df

     Name  age  Monthly Salary Team   Bonus
0  madhav   14          100000  CEO  1800.0
1  lalita   15            4000   DA   800.0
2  monika   16            5000  CTO  1000.0
3   Honey   17            3000   BA   600.0
4     ABC   21            2100   IT  1000.0

In [43]:
#delete value-row and column values
df.drop(df[df.Name=="ABC"].index) #drop row,axis=0

     Name  age  Monthly Salary Team   Bonus
0  madhav   14          100000  CEO  1800.0
1  lalita   15            4000   DA   800.0
2  monika   16            5000  CTO  1000.0
3   Honey   17            3000   BA   600.0

In [63]:
df.drop(1, axis=0) #index name

     Name  age  Salary Team
0  madhav   14  100000  CEO
2  monika   16    5000  CTO
3   Honey   17    3000   BA
4     ABC   21    2100   IT

In [64]:
df.drop('Bonus',axis=1, inplace=True, errors='ignore')
df

     Name  age  Salary Team
0  madhav   14  100000  CEO
2  monika   16    5000  CTO
1  lalita   15    4000   DA
3   Honey   17    3000   BA
4     ABC   21    2100   IT

In [53]:
#df.drop(['Team', 'Bonus'], axis=1, errors='ignore')  #delete multiple colums

     Name  age  Monthly Salary
0  madhav   14          100000
1  lalita   15            4000
2  monika   16            5000
3   Honey   17            3000
4     ABC   21            2100

In [55]:
df

     Name  age  Monthly Salary Team
0  madhav   14          100000  CEO
1  lalita   15            4000   DA
2  monika   16            5000  CTO
3   Honey   17            3000   BA
4     ABC   21            2100   IT

In [57]:
df.rename(columns={'Monthly Salary':'Salary'}, inplace=True)
df

     Name  age  Salary Team
0  madhav   14  100000  CEO
1  lalita   15    4000   DA
2  monika   16    5000  CTO
3   Honey   17    3000   BA
4     ABC   21    2100   IT

In [59]:
#sort value
df.sort_values('Salary') #ascending order by default

     Name  age  Salary Team
0  madhav   14  100000  CEO
2  monika   16    5000  CTO
1  lalita   15    4000   DA
3   Honey   17    3000   BA
4     ABC   21    2100   IT

In [61]:
df.sort_values('Salary', ascending=False) #descending order
df

     Name  age  Salary Team
0  madhav   14  100000  CEO
2  monika   16    5000  CTO
1  lalita   15    4000   DA
3   Honey   17    3000   BA
4     ABC   21    2100   IT

In [ ]:
#working with date dat type

In [65]:
df['DOJ']=['2024-01-01','2024-01-15','2024-03-28','2024-03-03','2024-01-01']
df

     Name  age  Salary Team         DOJ
0  madhav   14  100000  CEO  2024-01-01
2  monika   16    5000  CTO  2024-01-15
1  lalita   15    4000   DA  2024-03-28
3   Honey   17    3000   BA  2024-03-03
4     ABC   21    2100   IT  2024-01-01

In [66]:
df['DOJ'].dtype

dtype('O')

In [68]:
df['DOJ']=pd.to_datetime(df['DOJ'])
df['DOJ'].dtype

dtype('<M8[ns]')

In [70]:
df1=df

In [71]:
df1

     Name  age  Salary Team        DOJ
0  madhav   14  100000  CEO 2024-01-01
2  monika   16    5000  CTO 2024-01-15
1  lalita   15    4000   DA 2024-03-28
3   Honey   17    3000   BA 2024-03-03
4     ABC   21    2100   IT 2024-01-01

In [72]:
df1['DOJ2']=['01-01-2025','15-01-2025','28-03-2025','03-03-2025','01-01-2025']
df1

     Name  age  Salary Team        DOJ        DOJ2
0  madhav   14  100000  CEO 2024-01-01  01-01-2025
2  monika   16    5000  CTO 2024-01-15  15-01-2025
1  lalita   15    4000   DA 2024-03-28  28-03-2025
3   Honey   17    3000   BA 2024-03-03  03-03-2025
4     ABC   21    2100   IT 2024-01-01  01-01-2025

In [73]:
df1['DOJ2'].dtypes

dtype('O')

In [76]:
df1['DOJ2']=pd.to_datetime(df['DOJ2'], format='%d-%m-%Y')

In [78]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [83]:
df=df.drop('DOJ2',axis=1)

In [84]:
df

     Name  age  Salary Team        DOJ
0  madhav   14  100000  CEO 2024-01-01
2  monika   16    5000  CTO 2024-01-15
1  lalita   15    4000   DA 2024-03-28
3   Honey   17    3000   BA 2024-03-03
4     ABC   21    2100   IT 2024-01-01

In [90]:
#extract year, month,week day

df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
2      Monday
1    Thursday
3      Sunday
4      Monday
Name: DOJ, dtype: object

In [91]:
df['Month']=df['DOJ'].dt.month

In [92]:
df

     Name  age  Salary Team        DOJ  Month
0  madhav   14  100000  CEO 2024-01-01      1
2  monika   16    5000  CTO 2024-01-15      1
1  lalita   15    4000   DA 2024-03-28      3
3   Honey   17    3000   BA 2024-03-03      3
4     ABC   21    2100   IT 2024-01-01      1

In [93]:
df['DOJ']+pd.Timedelta(days=90)

0   2024-03-31
2   2024-04-14
1   2024-06-26
3   2024-06-01
4   2024-03-31
Name: DOJ, dtype: datetime64[ns]

In [96]:
df

     Name  age  Salary Team        DOJ  Month
0  madhav   14  100000  CEO 2024-01-01      1
2  monika   16    5000  CTO 2024-01-15      1
1  lalita   15    4000   DA 2024-03-28      3
3   Honey   17    3000   BA 2024-03-03      3
4     ABC   21    2100   IT 2024-01-01      1

#Handling missing values

In [94]:
df.isnull()

    Name    age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
2  False  False   False  False  False  False
1  False  False   False  False  False  False
3  False  False   False  False  False  False
4  False  False   False  False  False  False

In [97]:
import numpy as np

In [101]:
df.loc[df.Name=="Honey","Salary"]=np.nan

In [102]:
df

     Name  age    Salary Team        DOJ  Month
0  madhav   14  100000.0  CEO 2024-01-01      1
2  monika   16    5000.0  CTO 2024-01-15      1
1  lalita   15    4000.0   DA 2024-03-28      3
3   Honey   17       NaN   BA 2024-03-03      3
4     ABC   21    2100.0   IT 2024-01-01      1

In [103]:
df.isnull()

    Name    age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
2  False  False   False  False  False  False
1  False  False   False  False  False  False
3  False  False    True  False  False  False
4  False  False   False  False  False  False

In [104]:
df.isnull().sum()

Name      0
age       0
Salary    1
Team      0
DOJ       0
Month     0
dtype: int64

In [105]:
df.fillna(0)

     Name  age    Salary Team        DOJ  Month
0  madhav   14  100000.0  CEO 2024-01-01      1
2  monika   16    5000.0  CTO 2024-01-15      1
1  lalita   15    4000.0   DA 2024-03-28      3
3   Honey   17       0.0   BA 2024-03-03      3
4     ABC   21    2100.0   IT 2024-01-01      1

In [106]:
#Agregation and group by
df["Team"].value_counts()

Team
CEO    1
CTO    1
DA     1
BA     1
IT     1
Name: count, dtype: int64

In [107]:
df['Month'].value_counts()

Month
1    3
3    2
Name: count, dtype: int64

In [109]:
df[df['Month']==1].value_counts()

Name    age  Salary    Team  DOJ         Month
ABC     21   2100.0    IT    2024-01-01  1        1
madhav  14   100000.0  CEO   2024-01-01  1        1
monika  16   5000.0    CTO   2024-01-15  1        1
Name: count, dtype: int64

In [111]:
df.groupby('Month')['Salary'].sum() #aggregation based on group by

Month
1    107100.0
3      4000.0
Name: Salary, dtype: float64

In [113]:
df.groupby('Month').agg({'Salary':'mean','Name':'count'})

        Salary  Name
Month
1      35700.0     3
3       4000.0     2

###concatenate and merge dataframe(Joins)

In [115]:
df1=pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [116]:
df2=pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [117]:
pd.concat([df1,df2],axis=0) #vertical/row level/top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [118]:
pd.concat([df1,df2],axis=1) #Horizontal/column level/side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [119]:
#merge=join
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [123]:
pd.merge(df1,df2,how='right',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   4  NaN     79

In [124]:
pd.merge(df1,df2,how='left',on='ID') #we cna use left,right,inner,outer

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN

In [125]:
pd.merge(df1,df2,how="inner",left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77